universe = vanilla
+SingularityImage = "/cvmfs/containers.jinr.ru/taiga/containers/taiga_g4:el9"
executable = /bin/bash
transfer_executable = False
arguments = simulate_one.sh 10_iact_split_i assets parameters.txt
should_transfer_files = YES
transfer_input_files = simulate_one.sh,TAIGA_optics_file,assets,../converted/10_iact_split_i
transfer_output_files = result.bin,result_A_sums2,result.done
transfer_output_remaps = "result.bin=results/10_iact_split_feb;result_A_sums2=results/10_iact_split_A_sums2;result.done=results/10_iact_split.done"
when_to_transfer_output = ON_EXIT
log = logs/optics-$(ClusterId)-$(ProcId).log
output = logs/optics-$(ClusterId)-$(ProcId).out
error = logs/optics-$(ClusterId)-$(ProcId).err
accounting_group = taiga
request_cpus = 1
request_memory = 8GB
request_disk = 4GB
on_exit_hold = (ExitBySignal == True) || (ExitCode != 0)
queue 1
