universe = vanilla
executable = /bin/bash
transfer_executable = False
arguments = convert_one.sh $(input_name) $(radius)
runtime = runtime.tar.gz
radius = 100
transfer_input_files = convert_one.sh,$(runtime),$(input_file)
transfer_output_files = result_i,result_t,result.done
transfer_output_remaps = "result_i=$(output_prefix)_i;result_t=$(output_prefix)_t;result.done=$(output_prefix).done"
jobs_file = convert_jobs.tsv
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
log = logs/convert/$(ClusterId)-$(ProcId).log
output = logs/convert/$(ClusterId)-$(ProcId).out
error = logs/convert/$(ClusterId)-$(ProcId).err
accounting_group = taiga
request_cpus = 1
request_memory = 8GB
request_disk = 4GB
on_exit_hold = (ExitBySignal == True) || (ExitCode != 0)
queue input_file,input_name,output_prefix,output_suffix from $(jobs_file)
