universe = vanilla
+SingularityImage = "/cvmfs/containers.jinr.ru/taiga/containers/taiga_corsika:el9"
executable = /bin/bash
transfer_executable = False
arguments = test_convert_one.sh
should_transfer_files = YES
transfer_input_files = test_convert_one.sh,build/hybrid,/taiga/huseyin/optics/io_taiga/lib/libtaiga_io_eventio.so,/taiga/huseyin/optics/io_taiga/lib/libtaiga_io_text.so,/taiga/huseyin/1000m/E_200_2000TeV/test_3PeV/10_iact.corsika
transfer_output_files = 10_iact_split_i,10_iact_split_t
transfer_output_remaps = "10_iact_split_i=converted/10_iact_split_i;10_iact_split_t=converted/10_iact_split_t"
when_to_transfer_output = ON_EXIT
log = logs/test-$(ClusterId)-$(ProcId).log
output = logs/test-$(ClusterId)-$(ProcId).out
error = logs/test-$(ClusterId)-$(ProcId).err
accounting_group = taiga
request_cpus = 1
request_memory = 4GB
request_disk = 1GB
on_exit_hold = (ExitBySignal == True) || (ExitCode != 0)
queue 1
